server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: bamboo-zuul

zuul:
  routes:
    bamboo-consumer: /bamboo8080/**
  ignored-services: "*"