server:
  port: 8761

eureka:
  server:
    #心跳正常客户端百分比阈值
    renewal-percent-threshold: 0.85
    #自我保护机制，默认开启-true
    enable-self-preservation: true
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/